audit_log_path = "C:/temp/db_setup"

extensions_per_schema= ["btree_gist", "uuid-ossp"]

[connection_strings]
local = "server=localhost;Port=5432;Database=postgres;User Id=postgres;Password=root4me;Search Path=public;Include Error Detail=true"

[database_to_schema_map]
dev01 = "quick_setup"

[create_database_metadata]
owner = "postgres"
encoding = "UTF8"
tablespace = "pg_default"
connection_limit = -1

[owning_user_template]
name = "{{SCHEMA}}_machine_user_{{DATABASE}}"
password = "{{PASSWORD}}"

[[read_write_user_templates]]
name = "{{SCHEMA}}_app_user_{{DATABASE}}"
password = "{{PASSWORD}}"

[[readonly_user_templates]]
name = "{{SCHEMA}}_readonly_user_{{DATABASE}}"
password = "{{PASSWORD}}"
